#!/bin/bash

#ADCPROG=./seismoads.py

ADCPROG=$(dirname $0)/seismo1256.py

while true; do
  diskuse=$(df | awk '/^\/dev\/root/{print $5}' | sed 's/%//')
  [[ $diskuse -gt 80 ]] && exit
  $ADCPROG $@
done
