#!/bin/bash

while true; do
  diskuse=$(df | awk '/^\/dev\/root/{print $5}' | sed 's/%//')
  [[ $diskuse -gt 80 ]] && exit
  fname=$(date +'%Y%m%d%H%M%S').txt
  ./seismoads.py block=1024 N=10 > $fname
done
