#!/usr/bin/env python3

import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtWebKit import *
from PyQt5.QtWebKitWidgets import *
from PyQt5.QtWidgets import QApplication, QWidget, QMainWindow

host='http://localhost'
port='8000'
winmode='max'

for arg in sys.argv:
    if arg.find('host=') == 0:
        host=arg.replace('host=','')
        if host.find('http') != 0:
            host='http://'+host
    if arg.find('port=') == 0:
        port=arg.replace('port=','')
    if arg.find('mode=') == 0:
        winmode=arg.replace('mode=','')

app = QApplication(sys.argv)
web = QWebView()

print('loading '+host+':'+port)

web.resize(1000,600)
web.load(QUrl(host+':'+port))

if winmode == 'max':
    web.showMaximized()

web.show()

sys.exit(app.exec_())
